
services:
  database:
    image: mysql:8.0
    container_name: chemistry_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chemistryDB
    ports:
      - "3307:3306"  # Puerto estándar
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    networks:
      - chemistry_network

  api:
    build: .
    container_name: chemistry_api
    restart: always
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://chemistry_database:3306/chemistryDB?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root  # Cambié la contraseña a 'root' porque es la configurada en MYSQL_ROOT_PASSWORD
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "4000:4000"
    networks:
      - chemistry_network

volumes:
  mysql_data:

networks:
  chemistry_network:
    driver: bridge
